#pragma once

#include <cstdint>

namespace cs2::engine_trace {

using ContentsMask = std::uint64_t;
constexpr ContentsMask CONTENTS_EMPTY = 0x00000000ull;
constexpr ContentsMask CONTENTS_CATEGORY_SOLID = 0x00000001ull;
constexpr ContentsMask CONTENTS_CATEGORY_HITBOXES = 0x00000002ull;
constexpr ContentsMask CONTENTS_CATEGORY_TRIGGER = 0x00000004ull;
constexpr ContentsMask CONTENTS_CATEGORY_SKY = 0x00000008ull;
constexpr ContentsMask CONTENTS_CATEGORY_PLAYER_CLIP = 0x00000010ull;
constexpr ContentsMask CONTENTS_CATEGORY_NPC_CLIP = 0x00000020ull;
constexpr ContentsMask CONTENTS_CATEGORY_BLOCK_LOS = 0x00000040ull;
constexpr ContentsMask CONTENTS_CATEGORY_BLOCK_LIGHT = 0x00000080ull;
constexpr ContentsMask CONTENTS_CATEGORY_LADDER = 0x00000100ull;
constexpr ContentsMask CONTENTS_CATEGORY_PICKUP = 0x00000200ull;
constexpr ContentsMask CONTENTS_CATEGORY_BLOCK_SOUND = 0x00000400ull;
constexpr ContentsMask CONTENTS_CATEGORY_NO_DRAW = 0x00000800ull;
constexpr ContentsMask CONTENTS_CATEGORY_WINDOW = 0x00001000ull;
constexpr ContentsMask CONTENTS_CATEGORY_PASS_BULLETS = 0x00002000ull;
constexpr ContentsMask CONTENTS_CATEGORY_WORLD_GEOMETRY = 0x00004000ull;
constexpr ContentsMask CONTENTS_CATEGORY_WATER = 0x00008000ull;
constexpr ContentsMask CONTENTS_CATEGORY_SLIME = 0x00010000ull;
constexpr ContentsMask CONTENTS_CATEGORY_TOUCH_ALL = 0x00020000ull;
constexpr ContentsMask CONTENTS_CATEGORY_PLAYER = 0x00040000ull;
constexpr ContentsMask CONTENTS_CATEGORY_NPC = 0x00080000ull;
constexpr ContentsMask CONTENTS_CATEGORY_DEBRIS = 0x00100000ull;
constexpr ContentsMask CONTENTS_CATEGORY_PHYSICS_PROP = 0x00200000ull;
constexpr ContentsMask CONTENTS_CATEGORY_NAV_IGNORE = 0x00400000ull;
constexpr ContentsMask CONTENTS_CATEGORY_NAV_LOCAL_IGNORE = 0x00800000ull;
constexpr ContentsMask CONTENTS_CATEGORY_POST_PROCESSING_VOLUME = 0x01000000ull;
constexpr ContentsMask CONTENTS_CATEGORY_VEHICLE_CLIP = 0x02000000ull;
constexpr ContentsMask CONTENTS_CATEGORY_CARRIED_OBJECT = 0x04000000ull;
constexpr ContentsMask CONTENTS_CATEGORY_PUSH_AWAY = 0x08000000ull;
constexpr ContentsMask CONTENTS_CATEGORY_SERVER_ENTITY_ON_CLIENT = 0x10000000ull;
constexpr ContentsMask CONTENTS_CATEGORY_CARRIED_WEAPON = 0x20000000ull;
constexpr ContentsMask CONTENTS_CATEGORY_STATIC_LEVEL = 0x40000000ull;

constexpr ContentsMask CONTENTS_SOLID = CONTENTS_CATEGORY_SOLID | CONTENTS_CATEGORY_BLOCK_LOS | CONTENTS_CATEGORY_BLOCK_LIGHT | CONTENTS_CATEGORY_BLOCK_SOUND;
constexpr ContentsMask CONTENTS_SOLID_NO_BLOCK_LOS = CONTENTS_CATEGORY_SOLID | CONTENTS_CATEGORY_BLOCK_LIGHT | CONTENTS_CATEGORY_BLOCK_SOUND;


namespace observed_interacts_as {
    constexpr ContentsMask kWall = CONTENTS_CATEGORY_STATIC_LEVEL | CONTENTS_SOLID;
    constexpr ContentsMask kWindowDynamicProp = CONTENTS_CATEGORY_SERVER_ENTITY_ON_CLIENT | CONTENTS_CATEGORY_TOUCH_ALL | CONTENTS_CATEGORY_WINDOW | CONTENTS_CATEGORY_BLOCK_SOUND;
    constexpr ContentsMask kRailing = CONTENTS_CATEGORY_STATIC_LEVEL | CONTENTS_CATEGORY_PASS_BULLETS;
    constexpr ContentsMask kInteractiveDoor = CONTENTS_CATEGORY_SERVER_ENTITY_ON_CLIENT | CONTENTS_CATEGORY_PUSH_AWAY | CONTENTS_CATEGORY_TOUCH_ALL | CONTENTS_SOLID_NO_BLOCK_LOS;
    constexpr ContentsMask kVentCover = CONTENTS_CATEGORY_SERVER_ENTITY_ON_CLIENT | CONTENTS_CATEGORY_TOUCH_ALL | CONTENTS_CATEGORY_SOLID | CONTENTS_CATEGORY_BLOCK_LOS | CONTENTS_CATEGORY_BLOCK_LIGHT;
    constexpr ContentsMask kDynamicProp = CONTENTS_CATEGORY_SERVER_ENTITY_ON_CLIENT | CONTENTS_CATEGORY_TOUCH_ALL | CONTENTS_CATEGORY_SOLID | CONTENTS_CATEGORY_BLOCK_LIGHT;
    constexpr ContentsMask kBreakableProp = CONTENTS_CATEGORY_SERVER_ENTITY_ON_CLIENT | CONTENTS_CATEGORY_PHYSICS_PROP | CONTENTS_CATEGORY_DEBRIS | CONTENTS_CATEGORY_SOLID | CONTENTS_CATEGORY_BLOCK_LIGHT;
    constexpr ContentsMask kLadder = CONTENTS_CATEGORY_STATIC_LEVEL | CONTENTS_CATEGORY_PASS_BULLETS | CONTENTS_CATEGORY_LADDER;
    constexpr ContentsMask kPlayerEntity = CONTENTS_CATEGORY_SERVER_ENTITY_ON_CLIENT | CONTENTS_CATEGORY_TOUCH_ALL | CONTENTS_CATEGORY_PLAYER;
}
}
